apiVersion: v1
kind: Secret
metadata:
  name: connectify-secret
  namespace: connectify
type: Opaque
stringData:
  JWT_SECRET: change_me_for_k8s
  EMAIL: change_me@example.com
  PASS: change_me_app_password
